version: '3'

services:
  app_enlaces:
    build: enlaces
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://enlacedata_server:3306/enlacedata?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
      FRONTEND_URL: http://localhost:5173
    restart: always
    depends_on:
      enlacedata_server:
          condition: service_healthy
  enlacedata_server:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: enlacedata
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 4